apiVersion: v2
name: blinkchamber-platform
description: Plataforma completa de alta disponibilidad con ZITADEL, Vault, PostgreSQL y Redis
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Infraestructura base
  - name: cert-manager
    version: v1.13.3
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
    
  # Storage distribuido para videos
  - name: longhorn
    version: 1.6.0
    repository: https://charts.longhorn.io
    condition: longhorn.enabled
    
  # Base de datos
  - name: postgresql-ha
    version: 16.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
    
  # Cache y sesiones
  - name: redis
    version: 17.14.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    
  # Gestión de secretos
  - name: vault
    version: 0.25.0
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
    
  # Identidad y autenticación
  - name: zitadel
    version: 9.0.0
    repository: https://charts.zitadel.com
    condition: zitadel.enabled
    
  # Sistema de Email Completo
  - name: mailu
    version: 2.2.2
    repository: https://mailu.github.io/helm-charts
    condition: mailu.enabled

  # ========================================
  # STACK DE OBSERVABILIDAD
  # ========================================
  
  # Prometheus para métricas
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
    
  # Grafana para visualización
  - name: grafana
    version: 7.0.19
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.enabled
    
  # Loki para logs centralizados
  - name: loki
    version: 5.41.3
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.enabled
    
  # Promtail para recolección de logs
  - name: promtail
    version: 6.15.5
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.enabled

keywords:
  - identity
  - secrets
  - database
  - cache
  - high-availability
  - vault
  - zitadel
  - postgresql
  - redis
  - email
  - mailu
  - smtp
  - imap
  - webmail
  - monitoring
  - observability
  - prometheus
  - grafana
  - loki
  - logging

maintainers:
  - name: BlinkChamber Team
    email: team@blinkchamber.com

home: https://github.com/blinkchamber/platform
sources:
  - https://github.com/blinkchamber/platform 