apiVersion: v2
name: blinkchamber-platform
description: Plataforma completa de alta disponibilidad con ZITADEL, Vault y PostgreSQL
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Infraestructura base
  - name: cert-manager
    version: v1.13.3
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
    
  # Base de datos
  - name: postgresql-ha
    version: 12.5.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
    
  # Gestión de secretos
  - name: vault
    version: 0.25.0
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
    
  # Identidad y autenticación
  - name: zitadel
    version: 1.0.0
    repository: https://charts.zitadel.com
    condition: zitadel.enabled

keywords:
  - identity
  - secrets
  - database
  - high-availability
  - vault
  - zitadel
  - postgresql

maintainers:
  - name: BlinkChamber Team
    email: team@blinkchamber.com

home: https://github.com/blinkchamber/platform
sources:
  - https://github.com/blinkchamber/platform 