server:
  ha:
    enabled: true
    replicas: 3
  extraConfig: |
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_cert_file = "/vault/userconfig/tls/tls.crt"
      tls_key_file  = "/vault/userconfig/tls/tls.key"
      tls_disable   = false
    }
    storage "raft" {
      path    = "/vault/data"
      node_id = "vault-0"
    }
    api_addr = "https://vault.blinkchamber.svc:8200"
    cluster_addr = "https://vault.blinkchamber.svc:8201"
  extraVolumes:
    - type: secret
      name: vault-tls
      path: /vault/userconfig/tls
  extraVolumeMounts:
    - name: vault-tls
      mountPath: /vault/userconfig/tls
      readOnly: true
injector:
  enabled: true
ui:
  enabled: true
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi 