replicaCount: 2

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: zitadel.tu-dominio.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "zitadel-role"
  vault.hashicorp.com/agent-inject-secret-ZITADEL_DB_PASSWORD: "secret/data/zitadel/postgres#password"
  vault.hashicorp.com/agent-inject-template-ZITADEL_DB_PASSWORD: |
    {{- with secret "secret/data/zitadel/postgres" -}}
    {{ .Data.data.password }}
    {{- end }}
  vault.hashicorp.com/agent-inject-secret-VAULT_TOKEN: "secret/data/zitadel/vault#token"
  vault.hashicorp.com/agent-inject-template-VAULT_TOKEN: |
    {{- with secret "secret/data/zitadel/vault" -}}
    {{ .Data.data.token }}
    {{- end }}

config:
  database:
    postgres:
      host: postgres.tu-dominio.com
      port: 5432
      database: zitadel
      user: zitadel
      password:
        valueFromFile: /vault/secrets/ZITADEL_DB_PASSWORD
  secrets:
    vault:
      enabled: true
      address: "https://vault.blinkchamber.svc:8200"
      token:
        valueFromFile: /vault/secrets/VAULT_TOKEN
  externalDomain: zitadel.tu-dominio.com
  tls:
    enabled: true
    secretName: zitadel-tls

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80 