apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zitadel-chart.fullname" . }}
  labels:
    {{- include "zitadel-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zitadel-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "zitadel"
        vault.hashicorp.com/agent-inject-secret-masterkey: "secret/data/zitadel/masterkey"
        vault.hashicorp.com/agent-inject-template-masterkey: |
          {{`{{- with secret \"secret/data/zitadel/masterkey\" -}}\n{{ .Data.data.masterkey }}\n{{- end }}`}}
        vault.hashicorp.com/agent-inject-secret-db-password: "secret/data/zitadel/db-password"
        vault.hashicorp.com/agent-inject-template-db-password: |
          {{`{{- with secret \"secret/data/zitadel/db-password\" -}}\n{{ .Data.data.password }}\n{{- end }}`}}
        vault.hashicorp.com/agent-run-as-user: "1000"
      labels:
        {{- include "zitadel-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ZITADEL_MASTERKEY_PATH
              value: /vault/secrets/masterkey
            - name: ZITADEL_DATABASE_HOST
              value: {{ .Values.zitadel.database.host }}
            - name: ZITADEL_DATABASE_PORT
              value: {{ .Values.zitadel.database.port | quote }}
            - name: ZITADEL_DATABASE_USER
              value: {{ .Values.zitadel.database.user }}
            - name: ZITADEL_DATABASE_PASSWORD_PATH
              value: /vault/secrets/db-password
