replicaCount: 3

image:
  repository: "vault"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8200

vault:
  storage:
    raft:
      enabled: true
      path: "/vault/data"
  listener:
    tcp:
      address: "0.0.0.0:8200"
      cluster_address: "0.0.0.0:8201"
      tls_disable: true
  api_addr: "http://vault:8200"
  cluster_addr: "http://vault:8201"
