kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: blinkchamber
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            enable-admission-plugins: "NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 8200
        hostPort: 8200
        protocol: TCP
      - containerPort: 3000
        hostPort: 3000
        protocol: TCP
      - containerPort: 9000
        hostPort: 9000
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
        # PostgreSQL port disabled due to conflicts with local PostgreSQL
        # - containerPort: 5432
        #   hostPort: 5432
        #   protocol: TCP
    extraMounts:
      - hostPath: ./data
        containerPath: /data
        propagation: Bidirectional
  - role: worker
    labels:
      node-type: worker
      storage-node: "true"
  - role: worker
    labels:
      node-type: worker
      storage-node: "true"
  - role: worker
    labels:
      node-type: worker
      storage-node: "true"
# Configuración de networking
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: false
  kubeProxyMode: "iptables"
