apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.infra }}
  labels:
    name: {{ .Values.global.namespaces.infra }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.vault }}
  labels:
    name: {{ .Values.global.namespaces.vault }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.database }}
  labels:
    name: {{ .Values.global.namespaces.database }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.identity }}
  labels:
    name: {{ .Values.global.namespaces.identity }}
    app.kubernetes.io/part-of: {{ .Chart.Name }} 