{{- if .Values.zitadel.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-masterkey
  namespace: identity
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "zitadel-role"
    vault.hashicorp.com/agent-inject-secret-masterkey: "secret/data/zitadel/config#masterkey"
    vault.hashicorp.com/agent-inject-template-masterkey: |
      {{`{{- with secret "secret/data/zitadel/config" -}}
      {{ .Data.data.masterkey }}
      {{- end }}`}}
type: Opaque
data:
  masterkey: ""  # Se llenará por Vault Agent
{{- end }}
