{{- if .Values.grafana.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blinkchamber.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "blinkchamber.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "blinkchamber.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "monitoring-role"
        vault.hashicorp.com/agent-inject-secret-grafana: "secret/data/monitoring/grafana"
        vault.hashicorp.com/agent-inject-template-grafana: |
          {{- with secret "secret/data/monitoring/grafana" -}}
          export GF_SECURITY_ADMIN_USER='{{ .Data.data.admin_username }}'
          export GF_SECURITY_ADMIN_PASSWORD='{{ .Data.data.admin_password }}'
          {{- end }}
    spec:
      serviceAccountName: {{ include "blinkchamber.fullname" . }}-grafana-sa
      containers:
        - name: grafana
          image: grafana/grafana:10.2.2
          command: ["/bin/sh", "-c"]
          args:
            - |
              source /vault/secrets/grafana
              /run.sh
          ports:
            - containerPort: {{ .Values.grafana.service.port }}
              name: http
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      volumes:
        - name: grafana-storage
          {{- if .Values.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "blinkchamber.fullname" . }}-grafana-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blinkchamber.fullname" . }}-grafana-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
---
{{- if .Values.grafana.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "blinkchamber.fullname" . }}-grafana-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blinkchamber.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  selector:
    {{- include "blinkchamber.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
  - name: http
    port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.service.port }}
  type: {{ .Values.grafana.service.type }}
{{- if .Values.grafana.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blinkchamber.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
  tls:
  {{- range .Values.grafana.ingress.tls }}
    - hosts:
    {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.grafana.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "blinkchamber.fullname" $ }}-grafana
                port:
                  number: {{ $.Values.grafana.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}