{{- if .Values.zitadel.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "blinkchamber.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zitadel
  template:
    metadata:
      labels:
        {{- include "blinkchamber.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zitadel
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "identity-role"
        vault.hashicorp.com/agent-inject-secret-zitadel: "secret/data/identity/zitadel"
        vault.hashicorp.com/agent-inject-template-zitadel: |
          {{- with secret "secret/data/identity/zitadel" -}}
          export ZITADEL_MASTERKEY='{{ .Data.data.masterkey }}'
          export ZITADEL_ADMIN_USERNAME='{{ .Data.data.admin_username }}'
          export ZITADEL_ADMIN_PASSWORD='{{ .Data.data.admin_password }}'
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/database/postgres"
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/data/database/postgres" -}}
          export ZITADEL_DATABASE_POSTGRES_HOST='localhost'
          export ZITADEL_DATABASE_POSTGRES_PORT='5432'
          export ZITADEL_DATABASE_POSTGRES_DATABASE='{{ .Data.data.database }}'
          export ZITADEL_DATABASE_POSTGRES_USER_USERNAME='{{ .Data.data.username }}'
          export ZITADEL_DATABASE_POSTGRES_USER_PASSWORD='{{ .Data.data.password }}'
          export ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME='{{ .Data.data.username }}'
          export ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD='{{ .Data.data.password }}'
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mail: "secret/data/mail/postfix"
        vault.hashicorp.com/agent-inject-template-mail: |
          {{- with secret "secret/data/mail/postfix" -}}
          export ZITADEL_SMTP_HOST='{{ .Data.data.host }}'
          export ZITADEL_SMTP_PORT='{{ .Data.data.port }}'
          export ZITADEL_SMTP_USER='{{ .Data.data.user }}'
          export ZITADEL_SMTP_PASSWORD='{{ .Data.data.password }}'
          export ZITADEL_SMTP_FROM_ADDRESS='{{ .Data.data.from_address }}'
          export ZITADEL_SMTP_TLS='false'
          export ZITADEL_SMTP_STARTTLS='false'
          {{- end }}
    spec:
      serviceAccountName: {{ include "blinkchamber.fullname" . }}-zitadel-sa
      containers:
        - name: zitadel
          image: ghcr.io/zitadel/zitadel:v2.42.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              source /vault/secrets/zitadel
              source /vault/secrets/database
              source /vault/secrets/mail
              export ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
              export ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
              export ZITADEL_EXTERNALSECURE=false
              export ZITADEL_TLS_ENABLED=false
              /app/zitadel start-from-init --masterkey $ZITADEL_MASTERKEY --tlsMode disabled
          ports:
            - containerPort: {{ .Values.zitadel.service.port }}
              name: http
          livenessProbe:
            httpGet:
              path: /debug/healthz
              port: {{ .Values.zitadel.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /debug/ready
              port: {{ .Values.zitadel.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.zitadel.resources | nindent 12 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
spec:
  selector:
    {{- include "blinkchamber.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
  ports:
  - name: http
    port: {{ .Values.zitadel.service.port }}
    targetPort: {{ .Values.zitadel.service.port }}
  type: {{ .Values.zitadel.service.type }}
{{- if .Values.zitadel.ingress.enabled }}
---
apiVersion: networking.k8s.ioio/v1
kind: Ingress
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
  tls:
  {{- range .Values.zitadel.ingress.tls }}
    - hosts:
    {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.zitadel.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "blinkchamber.fullname" $ }}-zitadel
                port:
                  number: {{ $.Values.zitadel.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}