{{- if (eq (include "common.components.identity.enabled" .) "true") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "blinkchamber.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zitadel
  template:
    metadata:
      labels:
        {{- include "blinkchamber.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zitadel
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "identity-role"
        vault.hashicorp.com/agent-inject-secret-zitadel: "secret/data/identity/zitadel"
        vault.hashicorp.com/agent-inject-template-zitadel: |
          {{- with secret "secret/data/identity/zitadel" -}}
          export ZITADEL_MASTERKEY='{{ .Data.data.masterkey }}'
          export ZITADEL_ADMIN_USERNAME='{{ .Data.data.admin_username }}'
          export ZITADEL_ADMIN_PASSWORD='{{ .Data.data.admin_password }}'
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/database/postgres"
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/data/database/postgres" -}}
          export ZITADEL_DATABASE_POSTGRES_HOST='localhost'
          export ZITADEL_DATABASE_POSTGRES_PORT='5432'
          export ZITADEL_DATABASE_POSTGRES_DATABASE='{{ .Data.data.database }}'
          export ZITADEL_DATABASE_POSTGRES_USER_USERNAME='{{ .Data.data.username }}'
          export ZITADEL_DATABASE_POSTGRES_USER_PASSWORD='{{ .Data.data.password }}'
          export ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME='{{ .Data.data.username }}'
          export ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD='{{ .Data.data.password }}'
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mail: "secret/data/mail/postfix"
        vault.hashicorp.com/agent-inject-template-mail: |
          {{- with secret "secret/data/mail/postfix" -}}
          export ZITADEL_SMTP_HOST='{{ .Data.data.host }}'
          export ZITADEL_SMTP_PORT='{{ .Data.data.port }}'
          export ZITADEL_SMTP_USER='{{ .Data.data.user }}'
          export ZITADEL_SMTP_PASSWORD='{{ .Data.data.password }}'
          export ZITADEL_SMTP_FROM_ADDRESS='{{ .Data.data.from_address }}'
          export ZITADEL_SMTP_TLS='false'
          export ZITADEL_SMTP_STARTTLS='false'
          {{- end }}
    spec:
      serviceAccountName: {{ include "blinkchamber.fullname" . }}-zitadel-sa
      containers:
        - name: zitadel
          image: ghcr.io/zitadel/zitadel:v2.42.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              source /vault/secrets/zitadel
              source /vault/secrets/database
              source /vault/secrets/mail
              export ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
              export ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
              export ZITADEL_EXTERNALSECURE=false
              export ZITADEL_TLS_ENABLED=false
              /app/zitadel start-from-init --masterkey $ZITADEL_MASTERKEY --tlsMode disabled
          ports:
            - containerPort: {{ .Values.identity.zitadel_config.service.port }}
              name: http
          livenessProbe:
            httpGet:
              path: /debug/healthz
              port: {{ .Values.identity.zitadel_config.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /debug/ready
              port: {{ .Values.identity.zitadel_config.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.zitadel.resources | nindent 12 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel-vault-agent-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
data:
  agent-config.hcl: |
    exit_after_auth = false
    pid_file = "/tmp/vault-agent-pid"

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "zitadel-role"
        }
      }
      sink "file" {
        config = {
          path = "/vault/secrets/vault-token"
        }
      }
    }

    template {
      source      = "/vault/config/zitadel-masterkey.tpl"
      destination = "/vault/secrets/zitadel_masterkey"
    }

    template {
      source      = "/vault/config/zitadel-admin.tpl"
      destination = "/vault/secrets/zitadel_admin_username"
    }

    template {
      source      = "/vault/config/zitadel-admin-password.tpl"
      destination = "/vault/secrets/zitadel_admin_password"
    }

    template {
      source      = "/vault/config/postgres-username.tpl"
      destination = "/vault/secrets/postgres_username"
    }

    template {
      source      = "/vault/config/postgres-password.tpl"
      destination = "/vault/secrets/postgres_password"
    }

    vault {
      address = "http://{{ include "blinkchamber.fullname" . }}-vault:8200"
    }

  zitadel-masterkey.tpl: |
    {{`{{ with secret "secret/identity/zitadel" }}`}}
    {{`{{ .Data.data.masterkey }}`}}
    {{`{{ end }}`}}

  zitadel-admin.tpl: |
    {{`{{ with secret "secret/identity/zitadel" }}`}}
    {{`{{ .Data.data.admin_username }}`}}
    {{`{{ end }}`}}

  zitadel-admin-password.tpl: |
    {{`{{ with secret "secret/identity/zitadel" }}`}}
    {{`{{ .Data.data.admin_password }}`}}
    {{`{{ end }}`}}

  postgres-username.tpl: |
    {{`{{ with secret "secret/database/postgres" }}`}}
    {{`{{ .Data.data.username }}`}}
    {{`{{ end }}`}}

  postgres-password.tpl: |
    {{`{{ with secret "secret/database/postgres" }}`}}
    {{`{{ .Data.data.password }}`}}
    {{`{{ end }}`}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
spec:
  selector:
    {{- include "blinkchamber.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
  ports:
  - name: http
    port: {{ .Values.identity.zitadel_config.service.port }}
    targetPort: {{ .Values.identity.zitadel_config.service.port }}
  type: {{ .Values.identity.zitadel_config.service.type }}
{{- if .Values.identity.zitadel_config.ingress.enabled }}
---
apiVersion: networking.k8s.ioio/v1
kind: Ingress
metadata:
  name: {{ include "blinkchamber.fullname" . }}-zitadel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blinkchamber.labels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
  tls:
  {{- range .Values.identity.zitadel_config.ingress.tls }}
    - hosts:
    {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.identity.zitadel_config.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "blinkchamber.fullname" $ }}-zitadel
                port:
                  number: {{ $.Values.identity.zitadel_config.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}