# ========================================
# ENTORNO DE PRODUCCIÓN - MÁXIMA SEGURIDAD Y RECURSOS
# ========================================

# Heredar configuración base
import:
  - ../base/values.yaml

# ========================================
# OVERRIDES ESPECÍFICOS PARA PRODUCCIÓN
# ========================================

# Configuración global para producción
global:
  environment: "production"
  domain: "blinkchamber.com"
  
  # Configuración de TLS para producción
  tls:
    enabled: true
    certManager:
      enabled: true
      clusterIssuer: "letsencrypt-prod"  # Certificados de producción

# ========================================
# VAULT - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
vault:
  server:
    ha:
      replicas: 5  # Máxima disponibilidad
    extraConfig: |
      listener "tcp" {
        address = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        tls_cert_file = "/vault/userconfig/tls/tls.crt"
        tls_key_file  = "/vault/userconfig/tls/tls.key"
        tls_disable   = false
      }
      storage "raft" {
        path    = "/vault/data"
        node_id = "vault-0"
      }
      api_addr = "https://vault.blinkchamber.svc:8200"
      cluster_addr = "https://vault.blinkchamber.svc:8201"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi

# ========================================
# LONGHORN - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
longhorn:
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 3
  longhornManager:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
  longhornDriver:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
  longhornUI:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

# ========================================
# ALMACENAMIENTO DE VIDEOS - PRODUCCIÓN
# ========================================
videoStorage:
  longhorn:
    storageClass:
      name: "longhorn-videos"
      replicaCount: 3
      numberOfReplicas: 3
      staleReplicaTimeout: 2880
  volumes:
    uploads:
      size: 1Ti  # 1TB para videos subidos
      storageClass: "longhorn-videos"
      accessMode: ReadWriteMany
    processed:
      size: 5Ti  # 5TB para videos procesados
      storageClass: "longhorn-videos"
      accessMode: ReadWriteMany
    cache:
      size: 500Gi  # 500GB para cache
      storageClass: "longhorn-videos"
      accessMode: ReadWriteMany
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 8
      memory: 16Gi
  retention:
    days: 1095  # 3 años
    maxSize: "50Ti"  # 50TB máximo
  compression:
    enabled: true
    quality: "high"
    format: "mp4"

# ========================================
# POSTGRESQL - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
postgresql-ha:
  postgresql:
    primary:
      persistence:
        enabled: true
        size: 100Gi  # Tamaño grande para producción
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
    readReplicas:
      replicaCount: 3  # Tres réplicas para máxima disponibilidad
      persistence:
        enabled: true
        size: 100Gi
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
    pgpool:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi

# ========================================
# REDIS - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
redis:
  architecture: replication
  master:
    persistence:
      enabled: true
      size: 50Gi  # Tamaño grande para producción
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
  replica:
    replicaCount: 3  # Tres réplicas para máxima disponibilidad
    persistence:
      enabled: true
      size: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

# ========================================
# ZITADEL - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
zitadel:
  ingress:
    enabled: true
    hosts:
      - host: zitadel.blinkchamber.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: zitadel-tls
        hosts:
          - zitadel.blinkchamber.com
  
  zitadel:
    args: 
      - "start-from-init"
      - "--masterkeyFile"
      - "/vault/secrets/masterkey"
      - "--tlsMode"
      - "external"  # TLS terminado por Ingress en producción
    
    env:
      - name: ZITADEL_EXTERNALSECURE
        value: "true"  # HTTPS en producción
      - name: ZITADEL_EXTERNALDOMAIN
        value: "zitadel.blinkchamber.com"
    
    replicaCount: 3  # Tres réplicas para máxima disponibilidad
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    persistence:
      enabled: true
      size: 50Gi  # Tamaño grande para producción

# ========================================
# NGINX-INGRESS - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
ingress-nginx:
  controller:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

# ========================================
# CERT-MANAGER - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
cert-manager:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi





# ========================================
# MAILU - CONFIGURACIÓN PARA PRODUCCIÓN
# ========================================
mailu:
  # Configuración específica para producción
  hostnames:
    - mail.blinkchamber.com
  
  domain: "blinkchamber.com"
  
  # Recursos optimizados para producción
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi 

# ========================================
# STACK DE OBSERVABILIDAD - PRODUCCIÓN
# ========================================
monitoring:
  enabled: true
  
  # ========================================
  # PROMETHEUS - PRODUCCIÓN
  # ========================================
  prometheus:
    enabled: true
    alertmanager:
      enabled: true
      persistentVolume:
        enabled: true
        size: 20Gi
        storageClass: longhorn
    server:
      persistentVolume:
        enabled: true
        size: 100Gi
        storageClass: longhorn
      retention: 30d
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
    pushgateway:
      enabled: true
      persistentVolume:
        enabled: true
        size: 10Gi
        storageClass: longhorn
    configmapReload:
      enabled: true
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true

  # ========================================
  # GRAFANA - PRODUCCIÓN
  # ========================================
  grafana:
    enabled: true
    adminPassword: "admin123"  # Cambiar en producción
    persistence:
      enabled: true
      size: 20Gi
      storageClass: longhorn
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

  # ========================================
  # LOKI - PRODUCCIÓN
  # ========================================
  loki:
    enabled: true
    loki:
      auth_enabled: false
      commonConfig:
        path_prefix: /var/loki
        replication_factor: 1
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      ruler:
        alertmanager_url: http://prometheus-alertmanager
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
    persistence:
      enabled: true
      size: 50Gi
      storageClass: longhorn
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

  # ========================================
  # PROMTAIL - PRODUCCIÓN
  # ========================================
  promtail:
    enabled: true
    config:
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: http://loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: kubernetes-pods-name
          pipeline_stages:
            - docker: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_label_app
              target_label: app
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
              target_label: app
            - source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - source_labels:
                - __meta_kubernetes_pod_namespace
              target_label: namespace
            - source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - source_labels:
                - __meta_kubernetes_pod_name
                - __meta_kubernetes_pod_container_name
                - __meta_kubernetes_pod_container_port_name
              action: replace
              regex: (.+);(.+);(.+)
              replacement: $1:$2:$3
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels:
                - __meta_kubernetes_namespace
              action: replace
              target_label: namespace
            - source_labels:
                - __meta_kubernetes_pod_name
              action: replace
              target_label: pod
            - source_labels:
                - __meta_kubernetes_pod_container_name
              action: replace
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi 