apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vault-chart.fullname" . }}
  labels:
    {{- include "vault-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "vault-chart.fullname" . }}
  selector:
    matchLabels:
      {{- include "vault-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: cluster
              containerPort: 8201
              protocol: TCP
          env:
            - name: VAULT_API_ADDR
              value: "{{ .Values.vault.api_addr }}"
            - name: VAULT_CLUSTER_ADDR
              value: "{{ .Values.vault.cluster_addr }}"
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
