replicaCount: 2

image:
  repository: ghcr.io/zitadel/zitadel
  pullPolicy: IfNotPresent
  tag: "stable"

zitadel:
  database:
    host: "zitadel-postgresql"
    port: 5432
    user: "zitadel"

vault:
  address: "http://vault:8200"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: zitadel.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: zitadel-tls
     hosts:
       - zitadel.example.com
