replicaCount: 2

image:
  repository: ghcr.io/zitadel/zitadel
  pullPolicy: IfNotPresent
  tag: "stable"

zitadel:
  database:
    host: "zitadel-postgresql"
    port: 5432
    user: "zitadel"

vault:
  address: "http://vault:8200"
  role: "zitadel"
  secrets:
    masterkey: "secret/data/zitadel/masterkey"
    dbPassword: "secret/data/zitadel/db-password"

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: zitadel.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: zitadel-tls
     hosts:
       - zitadel.example.com
